INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000001, 'Tech Innovations', 'REG123456', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000002, 'Green Solutions', 'REG654321', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000003, 'Elite Construction', 'REG789456', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000004, 'Eco Energy', 'REG741852', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000005, 'Smart Tech Solutions', 'REG369258', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000006, 'BlueWave Logistics', 'REG753951', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000007, 'Urban Design Agency', 'REG147258', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000008, 'NextGen Marketing', 'REG852369', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000009, 'Precision Manufacturing', 'REG159753', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000010, 'Cloud AI Systems', 'REG951753', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000011, 'Quantum Dynamics', 'REG741963', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000012, 'Fusion Engineering', 'REG852147', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000013, 'SolarTech Solutions', 'REG963258', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000014, 'AI Innovators', 'REG147369', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000015, 'Eco Builders', 'REG753852', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000016, 'CyberSecure', 'REG258147', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000017, 'AgriFuture', 'REG369852', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000018, 'NextGen Robotics', 'REG852753', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000019, 'BlueSky Consulting', 'REG951357', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000020, 'Virtual Solutions', 'REG147258', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000021, 'SecureData Analytics', 'REG753159', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000022, 'Automated Systems Ltd.', 'REG159357', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000023, 'Web Architects', 'REG258369', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000024, 'FinTech Ventures', 'REG369147', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000025, 'HealthTech Innovations', 'REG159753', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000026, 'Urban Eco Ventures', 'REG753951', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000027, 'Smart Manufacturing Ltd.', 'REG852741', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000028, 'Sustainable Energy Co.', 'REG369852', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000029, 'Innovative Software', 'REG258369', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000030, 'Advanced Engineering Group', 'REG147258', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000031, 'NextGen AI Solutions', 'REG753159', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000032, 'EcoTech Industries', 'REG951753', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000033, 'Elite Marketing Agency', 'REG159753', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000034, 'BlueWave Design Studio', 'REG369147', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000035, 'Precision Security Systems', 'REG258741', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000036, 'Quantum Data Analytics', 'REG789456', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000037, 'Cloud IT Solutions', 'REG741963', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000038, 'Tech Frontier Consulting', 'REG852753', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000039, 'AI Driven Technologies', 'REG963258', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000040, 'Green Architectural Designs', 'REG147369', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000041, 'Cybernetic Solutions', 'REG753852', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000042, 'Agritech Innovations', 'REG258147', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000043, 'Automated Business Systems', 'REG369852', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000044, 'Renewable Power Solutions', 'REG852369', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000045, 'Corporate Branding Experts', 'REG159753', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000046, 'Cloud AI Robotics', 'REG951753', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000047, 'SecureTech Innovations', 'REG753159', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000048, 'HealthTech Solutions', 'REG258369', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000049, 'Web Development Hub', 'REG369147', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000050, 'Finance Analytics Group', 'REG159753', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000051, 'Kgosi Farming Co.', 'REG741258', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000052, 'Tshiamo Spaza', 'REG852369', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000053, 'Mahlatsi Fresh Produce', 'REG963147', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000054, 'Modise Mechanics', 'REG147369', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000055, 'Lethabo General Dealer', 'REG753852', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000056, 'Ntokozo Livestock Farm', 'REG258741', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000057, 'Dipuo Hair Salon', 'REG369852', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000058, 'Siyabonga Car Wash', 'REG852753', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000059, 'Mokgadi Bakery', 'REG963258', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000060, 'Bongiwe Poultry Farm', 'REG147369', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000061, 'Reagile Welding Works', 'REG753852', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000062, 'Mpho Funeral Services', 'REG258741', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000063, 'Tebogo Transport & Logistics', 'REG369852', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000064, 'Kganya Construction', 'REG852753', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000065, 'Lebogang Creche & Preschool', 'REG963258', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000066, 'Bafana Security Services', 'REG147369', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000067, 'Gogo’s Traditional Wear', 'REG753852', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000068, 'Vuyo Electronics Repairs', 'REG258741', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000069, 'Phindile Tuckshop', 'REG369852', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000070, 'Diketso Events & Catering', 'REG852753', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000071, 'Tshepo Brickworks', 'REG963258', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000072, 'Lerato Sewing & Tailoring', 'REG147369', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000073, 'Jabulani Auto Parts', 'REG753852', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000074, 'Sipho Water Delivery', 'REG258741', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000075, 'Nomzamo Health & Beauty', 'REG369852', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000076, 'Langa Upholstery', 'REG741258', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000077, 'Tumi Chicken Farm', 'REG852369', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000078, 'Dineo Fruit & Veg', 'REG963147', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000079, 'Mpumi Beauty Salon', 'REG147369', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000080, 'Sekhukhune Panel Beaters', 'REG753852', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000081, 'Mandla Construction', 'REG258741', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000082, 'Ntokozo Car Wash', 'REG369852', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000083, 'Bheki Plumbing Services', 'REG852753', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000084, 'Zodwa School Transport', 'REG963258', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000085, 'Kamo Solar Installations', 'REG147369', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000086, 'Mogale Hardware Store', 'REG753852', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000087, 'Sipho’s Spaza Shop', 'REG258741', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000088, 'Nomonde Catering Services', 'REG369852', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000089, 'Dakalo Taxi Service', 'REG852753', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000090, 'Thabo Electrical Repairs', 'REG963258', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000091, 'Palesa Kidswear Designs', 'REG147369', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000092, 'Zulu Brick Suppliers', 'REG753852', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000093, 'Rural Fresh Dairy', 'REG258741', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000094, 'Bafana Waste Removal', 'REG369852', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000095, 'Lethabo Security Services', 'REG852753', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000096, 'Vusi Woodworks', 'REG963258', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000097, 'Tsepo Welding & Steel', 'REG147369', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000098, 'Mpho Daycare Centre', 'REG753852', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000099, 'Siyabonga Water Supply', 'REG258741', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000100, 'Thandiwe Fashion Boutique', 'REG369852', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000101, 'Lebo Farming Supplies', 'REG741852', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000102, 'Masego Traditional Wear', 'REG852147', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000103, 'Thuli Fresh Produce', 'REG963258', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000104, 'Kagiso Panel Beaters', 'REG147369', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000105, 'Modise Transport Services', 'REG753852', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000106, 'Sindi Poultry Farm', 'REG258741', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000107, 'Bongani Mobile Car Wash', 'REG369852', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000108, 'Siphesihle Bakery', 'REG852753', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000109, 'Malebo Welding & Repairs', 'REG963258', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000110, 'Mandla Hardware & Building', 'REG147369', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000111, 'Zulu Fashion & Textiles', 'REG753852', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000112, 'Gogo’s Herbal Remedies', 'REG258741', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000113, 'Bafana Auto Repairs', 'REG369852', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000114, 'Palesa Catering & Events', 'REG852753', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000115, 'Sekhukhune Brick Makers', 'REG963258', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000116, 'Mokgadi Kidswear Designs', 'REG147369', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000117, 'Jabulani Transport Services', 'REG753852', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000118, 'Sipho Water Delivery', 'REG258741', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000119, 'Nomzamo Health & Beauty', 'REG369852', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000120, 'Langa Upholstery & Furniture', 'REG852753', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000121, 'Thabo Agricultural Supplies', 'REG963258', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000122, 'Tebogo Mobile Butchery', 'REG147369', 'small');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000123, 'Dineo Textile Manufacturing', 'REG753852', 'medium');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000124, 'Mpumi Event Management', 'REG258741', 'large');

INSERT INTO BUSINESS_LOAN (LOAN_ID, BUSINESS_NAME, BUSINESS_REGISTRATION_NUM, BUSINESS_TYPE) 
VALUES 
(100000125, 'Mandla Welding Works', 'REG369852', 'small');


