-- DROP TABLES FIRST (Safe Order)
DROP TABLE LOAN_REPAYMENT CASCADE CONSTRAINTS;
DROP TABLE TRANSACTION CASCADE CONSTRAINTS;
DROP TABLE CREDIT_RISK_ASSESSMENT CASCADE CONSTRAINTS;
DROP TABLE STUDENT_LOAN CASCADE CONSTRAINTS;
DROP TABLE BUSINESS_LOAN CASCADE CONSTRAINTS;
DROP TABLE PERSONAL_LOAN CASCADE CONSTRAINTS;
DROP TABLE LOAN CASCADE CONSTRAINTS;
DROP TABLE LOAN_APPLICATION CASCADE CONSTRAINTS;
DROP TABLE CARD CASCADE CONSTRAINTS;
DROP TABLE GROUP_SAVINGS_ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE FIXED_DEPOSIT_ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE CURRENT_ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE SAVINGS_ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER_IN_GROUP CASCADE CONSTRAINTS;
DROP TABLE GROUP_ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE ACCOUNTANT CASCADE CONSTRAINTS;
DROP TABLE IT_STAFF CASCADE CONSTRAINTS;
DROP TABLE TELLER CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;

-- CUSTOMER table
CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(100) NOT NULL,
    CUSTOMER_LNAME VARCHAR2(100),
    CUSTOMER_CELLNUM VARCHAR2(15) UNIQUE,
    CUSTOMER_ADDRESS VARCHAR2(100),
    CUSTOMER_DATE_OF_BIRTH DATE,
    CUSTOMER_EMAIL VARCHAR2(100) UNIQUE,
    ACTIVE_STATUS CHAR(1)
);

-- ACCOUNT table
CREATE TABLE ACCOUNT (
    ACCOUNT_ID INT PRIMARY KEY,
    CUSTOMER_ID INT CONSTRAINT CUST_FK REFERENCES CUSTOMER(CUSTOMER_ID),
    ACCOUNT_NUMBER VARCHAR2(255),
    BALANCE DECIMAL(10, 2),
    OPEN_DATE DATE,
    ACCOUNT_TYPE VARCHAR2(50),
    STATUS VARCHAR2(20),
    MONTHLY_FEE DECIMAL(10, 2)
);

-- SAVINGS_ACCOUNT
CREATE TABLE SAVINGS_ACCOUNT (
    ACCOUNT_ID INT PRIMARY KEY CONSTRAINT SAV_ACC_FK REFERENCES ACCOUNT(ACCOUNT_ID),
    INTEREST_RATE DECIMAL(5, 2) NOT NULL,
    WITHDRAWAL_LIMIT INT,
    SAVINGS_ACC_TYPE VARCHAR2(20) NOT NULL,
    FLAG CHAR(1) DEFAULT 'S'
);

-- CURRENT_ACCOUNT
CREATE TABLE CURRENT_ACCOUNT (
    ACCOUNT_ID INT PRIMARY KEY CONSTRAINT CUR_ACC_FK REFERENCES ACCOUNT(ACCOUNT_ID),
    OVERDRAFT_LIMIT DECIMAL(15, 2) NOT NULL,
    FLAG CHAR(1) DEFAULT 'C'
);

-- FIXED_DEPOSIT_ACCOUNT
CREATE TABLE FIXED_DEPOSIT_ACCOUNT (
    ACCOUNT_ID INT PRIMARY KEY CONSTRAINT FIX_DEP_ACC REFERENCES ACCOUNT(ACCOUNT_ID),
    DEPOSIT_TERM INT NOT NULL,
    INITIAL_DEPOSIT DECIMAL(15, 2) NOT NULL,
    EARLYWITHDRAWAL_PENALTY DECIMAL(5, 2) NOT NULL,
    MATURITY_DATE DATE NOT NULL,
    FLAG CHAR(1) DEFAULT 'F'
);

-- GROUP_SAVINGS_ACCOUNT
CREATE TABLE GROUP_SAVINGS_ACCOUNT (
    ACCOUNT_ID INT PRIMARY KEY CONSTRAINT GROUP_SAV_FK REFERENCES SAVINGS_ACCOUNT(ACCOUNT_ID),
    CONTRIBUTION_FREQUENCY VARCHAR2(10) NOT NULL,
    CONTRIBUTION_AMOUNT DECIMAL(15, 2) NOT NULL,
    FLAG CHAR(1) DEFAULT 'G'
);

-- GROUP_ACCOUNT (restructured)
CREATE TABLE GROUP_ACCOUNT (
    GROUP_ID INT PRIMARY KEY,
    ACCOUNT_ID INT CONSTRAINT GROUP_ACC_FK REFERENCES SAVINGS_ACCOUNT(ACCOUNT_ID),
    GROUP_NAME VARCHAR2(100) NOT NULL,
    JOINING_DATE DATE NOT NULL,
    LEADER_NAME VARCHAR2(100)
);



CREATE TABLE CUSTOMER_IN_GROUP (
    GROUP_ID INT CONSTRAINT GROUP_GRP_FK REFERENCES GROUP_ACCOUNT(GROUP_ID),
    CUSTOMER_ID INT CONSTRAINT CUST_GRP_FK REFERENCES CUSTOMER(CUSTOMER_ID),
    MEMBER_ROLE VARCHAR2(50),
    PRIMARY KEY (GROUP_ID, CUSTOMER_ID)
);
-- CARD
CREATE TABLE CARD (
    CARD_ID INT PRIMARY KEY,
    ACCOUNT_ID INT NOT NULL CONSTRAINT CARD_FK REFERENCES ACCOUNT(ACCOUNT_ID),
    CARD_NUMBER VARCHAR2(16) NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    ISSUE_DATE DATE NOT NULL,
    CARD_PIN VARCHAR2(4) NOT NULL,
    CVV_EVC VARCHAR2(3) NOT NULL
);

-- LOAN_APPLICATION
CREATE TABLE LOAN_APPLICATION (
    APPLICATION_ID INT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL CONSTRAINT LOANAPP_CUST_FK REFERENCES CUSTOMER(CUSTOMER_ID),
    LOAN_TYPE VARCHAR2(50) NOT NULL,
    PURPOSE_OF_LOAN VARCHAR2(100) NOT NULL,
    APPLICATION_STATUS CHAR(1) NOT NULL
);

-- EMPLOYEE
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT PRIMARY KEY,
    EMP_FNAME VARCHAR2(50) NOT NULL,
    EMP_LNAME VARCHAR2(50) NOT NULL,
    EMP_EMAIL VARCHAR2(100) UNIQUE,
    EMP_CELLNUM VARCHAR2(15),
    EMP_ADDRESS VARCHAR2(50),
    EMP_DATE_OF_HIRE DATE NOT NULL,
    EMP_TYPE VARCHAR2(20) NOT NULL
);

-- ACCOUNTANT
CREATE TABLE ACCOUNTANT (
    EMPLOYEE_ID INT PRIMARY KEY CONSTRAINT ACC_EMP_FK REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CERTIFICATION VARCHAR2(100),
    YEARS_OF_EXPERIENCE INT,
    SPECIALIZATION VARCHAR2(100),
    FLAG CHAR(1) DEFAULT 'A'
);

-- IT_STAFF
CREATE TABLE IT_STAFF (
    EMPLOYEE_ID INT PRIMARY KEY CONSTRAINT IT_EMP_FK REFERENCES EMPLOYEE(EMPLOYEE_ID),
    SPECIALIZATION VARCHAR2(100),
    PROJECTS_ASSIGNED INT,
    SYSTEM_ACCESS_LEVEL VARCHAR2(50),
    FLAG CHAR(1) DEFAULT 'I'
);

-- TELLER
CREATE TABLE TELLER (
    EMPLOYEE_ID INT PRIMARY KEY CONSTRAINT TELLER_EMP_FK REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CASH_HANDLING_LIMIT DECIMAL(15, 2),
    CUSTOMER_RATING DECIMAL(3, 2),
    FLAG CHAR(1) DEFAULT 'T'
);

-- LOAN
CREATE TABLE LOAN (
    LOAN_ID INT PRIMARY KEY,
    APPLICATION_ID INT NOT NULL CONSTRAINT LOAN_APP_FK REFERENCES LOAN_APPLICATION(APPLICATION_ID),
    CUSTOMER_ID INT NOT NULL CONSTRAINT LOAN_CUST_FK REFERENCES CUSTOMER(CUSTOMER_ID),
    INITIAL_LOAN_AMOUNT DECIMAL(15, 2) NOT NULL,
    INTEREST_RATE DECIMAL(5, 2) NOT NULL,
    LOAN_TERM INT NOT NULL,
    DISBURSEMENT_DATE DATE,
    REPAYMENT_FREQUENCY VARCHAR2(20),
    OUTSTANDING_AMOUNT DECIMAL(15, 2) NOT NULL
);

-- STUDENT_LOAN
CREATE TABLE STUDENT_LOAN (
    LOAN_ID INT PRIMARY KEY CONSTRAINT STU_LOAN_FK REFERENCES LOAN(LOAN_ID),
    REGISTRATION_STATUS VARCHAR2(20) NOT NULL,
    ACADEMIC_YEAR VARCHAR2(9) NOT NULL,
    INSTITUTION_NAME VARCHAR2(100) NOT NULL,
    STUDENT_NUM VARCHAR2(20) NOT NULL,
    ACADEMIC_AVERAGE DECIMAL(4, 2),
    SUBJECT_NAME VARCHAR2(100),
    FLAG CHAR(1) DEFAULT 'S'
);

-- BUSINESS_LOAN
CREATE TABLE BUSINESS_LOAN (
    LOAN_ID INT PRIMARY KEY CONSTRAINT BUS_LOAN_FK REFERENCES LOAN(LOAN_ID),
    BUSINESS_NAME VARCHAR2(100) NOT NULL,
    BUSINESS_REGISTRATION_NUM VARCHAR2(30) NOT NULL,
    BUSINESS_TYPE VARCHAR2(50) NOT NULL,
    FLAG CHAR(1) DEFAULT 'B'
);

-- PERSONAL_LOAN
CREATE TABLE PERSONAL_LOAN (
    LOAN_ID INT PRIMARY KEY CONSTRAINT PER_LOAN_FK REFERENCES LOAN(LOAN_ID),
    EMPLOYMENT_STATUS VARCHAR2(20) NOT NULL,
    MONTHLY_INCOME DECIMAL(15, 2),
    LOAN_PURPOSE VARCHAR2(50),
    FLAG CHAR(1) DEFAULT 'P'
);

-- CREDIT_RISK_ASSESSMENT
CREATE TABLE CREDIT_RISK_ASSESSMENT (
    ASSESSMENT_ID INT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL CONSTRAINT CRA_CUST_FK REFERENCES CUSTOMER(CUSTOMER_ID),
    APPLICATION_ID INT NOT NULL CONSTRAINT CRA_APP_FK REFERENCES LOAN_APPLICATION(APPLICATION_ID),
    LASTASSESSMENT_DATE DATE NOT NULL,
    CREDIT_SCORE INT,
    RISK_LEVEL VARCHAR2(20)
);

-- TRANSACTION
CREATE TABLE TRANSACTION (
    TRANSACTION_ID INT PRIMARY KEY,
    ACCOUNT_ID INT NOT NULL CONSTRAINT TRANS_ACC_FK REFERENCES ACCOUNT(ACCOUNT_ID),
    TRANSACTION_TIME DATE DEFAULT SYSDATE NOT NULL,
    TRANSACTION_TYPE VARCHAR2(20) NOT NULL,
    TRANSACTION_AMOUNT DECIMAL(15, 2) NOT NULL,
    TRANSACTION_DATE DATE NOT NULL
);

-- LOAN_REPAYMENT
CREATE TABLE LOAN_REPAYMENT (
    REPAYMENT_ID INT PRIMARY KEY,
    TRANSACTION_ID INT NOT NULL CONSTRAINT REPAY_TRANS_FK REFERENCES TRANSACTION(TRANSACTION_ID),
    LOAN_ID INT NOT NULL CONSTRAINT REPAY_LOAN_FK REFERENCES LOAN(LOAN_ID),
    PAYMENT_DATE DATE NOT NULL,
    PAYMENT_AMOUNT DECIMAL(15, 2) NOT NULL,
    PAYMENT_METHOD VARCHAR2(20) NOT NULL
);
