INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (101, 1, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (202, 2, 'Business', 'Agricultural Equipment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (303, 1, 'Personal', 'Home Renovation', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (404, 3, 'Student', 'Education', 'P');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (505, 4, 'Business', 'Small Business', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (606, 5, 'Personal', 'Medical Expenses', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (707, 6, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (808, 7, 'Business', 'Livestock Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (909, 8, 'Personal', 'Debt Consolidation', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (1010, 9, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (1111, 10, 'Business', 'Equipment Financing', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (1212, 11, 'Personal', 'Home Improvement', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (1313, 12, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (1414, 13, 'Business', 'Franchise Investment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (1515, 14, 'Personal', 'Emergency Fund', 'P');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (1616, 15, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (1717, 16, 'Business', 'Inventory Purchase', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (1818, 17, 'Personal', 'Vacation', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (1919, 18, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (2020, 19, 'Business', 'Marketing Strategy', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (2121, 20, 'Personal', 'Medical Bills', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (2222, 21, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (2323, 22, 'Business', 'Real Estate Investment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (2424, 23, 'Personal', 'Car Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (2525, 24, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (2626, 25, 'Business', 'Expansion Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (2727, 26, 'Personal', 'Home Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (2828, 27, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (2929, 28, 'Business', 'New Equipment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (3030, 29, 'Personal', 'Debt Relief', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (3131, 30, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (3232, 31, 'Business', 'Working Capital', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (3333, 32, 'Personal', 'Home Renovation', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (3434, 33, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (3535, 34, 'Business', 'Franchise Fees', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (3636, 35, 'Personal', 'Medical Expenses', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (3737, 36, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (3838, 37, 'Business', 'Marketing Expenses', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (3939, 38, 'Personal', 'Travel Expenses', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (4040, 39, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (4141, 40, 'Business', 'Product Development', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (4242, 41, 'Personal', 'Home Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (4343, 42, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (4444, 43, 'Business', 'Operational Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (4545, 44, 'Personal', 'Emergency Fund', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (4646, 45, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (4747, 46, 'Business', 'Inventory Purchase', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (4848, 47, 'Personal', 'Debt Consolidation', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (4949, 48, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (5050, 49, 'Business', 'Franchise Investment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (5151, 50, 'Personal', 'Medical Bills', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (5252, 51, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (5353, 52, 'Business', 'Marketing Strategy', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (5454, 53, 'Personal', 'Home Improvement', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (5555, 54, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (5656, 55, 'Business', 'Equipment Financing', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (5757, 56, 'Personal', 'Emergency Fund', 'P');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (5858, 57, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (5959, 58, 'Business', 'Livestock Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (6060, 59, 'Personal', 'Debt Consolidation', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (6161, 60, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (6262, 61, 'Business', 'New Equipment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (6363, 62, 'Personal', 'Home Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (6464, 63, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (6565, 64, 'Business', 'Expansion Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (6666, 65, 'Personal', 'Car Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (6767, 66, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (6868, 67, 'Business', 'Operational Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (6969, 68, 'Personal', 'Vacation', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (7070, 69, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (7171, 70, 'Business', 'Working Capital', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (7272, 71, 'Personal', 'Home Improvement', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (7373, 72, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (7474, 73, 'Business', 'Marketing Expenses', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (7575, 74, 'Personal', 'Travel Expenses', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (7676, 75, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (7777, 76, 'Business', 'Product Development', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (7878, 77, 'Personal', 'Home Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (7979, 78, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (8080, 79, 'Business', 'Operational Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (8181, 80, 'Personal', 'Emergency Fund', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (8282, 81, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (8383, 82, 'Business', 'Inventory Purchase', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (8484, 83, 'Personal', 'Debt Consolidation', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (8585, 84, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (8686, 85, 'Business', 'Franchise Investment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (8787, 86, 'Personal', 'Medical Bills', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (8888, 87, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (8989, 88, 'Business', 'Marketing Strategy', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (9090, 89, 'Personal', 'Home Improvement', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (9191, 90, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (9292, 91, 'Business', 'Equipment Financing', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (9393, 92, 'Personal', 'Emergency Fund', 'P');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (9494, 93, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (9595, 94, 'Business', 'Livestock Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (9696, 95, 'Personal', 'Debt Consolidation', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (9797, 96, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (9898, 97, 'Business', 'New Equipment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (9999, 98, 'Personal', 'Home Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (10000, 99, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (10101, 100, 'Business', 'Expansion Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (10202, 101, 'Personal', 'Car Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (10303, 102, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (10404, 103, 'Business', 'Operational Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (10505, 104, 'Personal', 'Emergency Fund', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (10606, 105, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (10707, 106, 'Business', 'Inventory Purchase', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (10808, 107, 'Personal', 'Debt Consolidation', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (10909, 108, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (11010, 109, 'Business', 'Franchise Investment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (11111, 110, 'Personal', 'Medical Bills', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (11212, 111, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (11313, 112, 'Business', 'Marketing Strategy', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (11414, 113, 'Personal', 'Home Improvement', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (11515, 114, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (11616, 115, 'Business', 'Equipment Financing', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (11717, 116, 'Personal', 'Emergency Fund', 'P');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (11818, 117, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (11919, 118, 'Business', 'Livestock Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (12020, 119, 'Personal', 'Debt Consolidation', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (12121, 120, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (12222, 121, 'Business', 'New Equipment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (12323, 122, 'Personal', 'Home Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (12424, 123, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (12525, 124, 'Business', 'Expansion Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (12626, 125, 'Personal', 'Car Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (12727, 126, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (12828, 127, 'Business', 'Operational Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (12929, 128, 'Personal', 'Emergency Fund', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (13030, 129, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (13131, 130, 'Business', 'Inventory Purchase', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (13232, 131, 'Personal', 'Debt Consolidation', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (13333, 132, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (13434, 133, 'Business', 'Franchise Investment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (13535, 134, 'Personal', 'Medical Bills', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (13636, 135, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (13737, 136, 'Business', 'Marketing Strategy', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (13838, 137, 'Personal', 'Home Improvement', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (13939, 138, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (14040, 139, 'Business', 'Equipment Financing', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (14141, 140, 'Personal', 'Emergency Fund', 'P');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (14242, 141, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (14343, 142, 'Business', 'Livestock Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (14444, 143, 'Personal', 'Debt Consolidation', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (14545, 144, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (14646, 145, 'Business', 'New Equipment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (14747, 146, 'Personal', 'Home Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (14848, 147, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (14949, 148, 'Business', 'Expansion Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15050, 149, 'Personal', 'Car Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15151, 150, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15152, 151, 'Business', 'New Equipment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15153, 152, 'Personal', 'Home Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15154, 153, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15155, 154, 'Business', 'Expansion Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15156, 155, 'Personal', 'Car Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15157, 156, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15158, 157, 'Business', 'Operational Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15159, 158, 'Personal', 'Emergency Fund', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15160, 159, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15161, 160, 'Business', 'Inventory Purchase', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15162, 161, 'Personal', 'Debt Consolidation', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15163, 162, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15164, 163, 'Business', 'Franchise Investment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15165, 164, 'Personal', 'Medical Bills', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15166, 165, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15167, 166, 'Business', 'Marketing Strategy', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15168, 167, 'Personal', 'Home Improvement', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15169, 168, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15170, 169, 'Business', 'Equipment Financing', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15171, 170, 'Personal', 'Emergency Fund', 'P');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15172, 171, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15173, 172, 'Business', 'Livestock Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15174, 173, 'Personal', 'Debt Consolidation', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15175, 174, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15176, 175, 'Business', 'New Equipment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15177, 176, 'Personal', 'Home Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15178, 177, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15179, 178, 'Business', 'Expansion Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15180, 179, 'Personal', 'Car Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15181, 180, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15182, 181, 'Business', 'Operational Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15183, 182, 'Personal', 'Emergency Fund', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15184, 183, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15185, 184, 'Business', 'Inventory Purchase', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15186, 185, 'Personal', 'Debt Consolidation', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15187, 186, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15188, 187, 'Business', 'Franchise Investment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15189, 188, 'Personal', 'Medical Bills', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15190, 189, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15191, 190, 'Business', 'Marketing Strategy', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15192, 191, 'Personal', 'Home Improvement', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15193, 192, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15194, 193, 'Business', 'Equipment Financing', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15195, 194, 'Personal', 'Emergency Fund', 'P');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15196, 195, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15197, 196, 'Business', 'Livestock Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15198, 197, 'Personal', 'Debt Consolidation', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15199, 198, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15200, 199, 'Business', 'New Equipment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15201, 200, 'Personal', 'Home Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15205, 201, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15211, 202, 'Business', 'New Equipment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15217, 203, 'Personal', 'Home Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15223, 204, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15229, 205, 'Business', 'Expansion Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15235, 206, 'Personal', 'Car Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15241, 207, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15247, 208, 'Business', 'Operational Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15253, 209, 'Personal', 'Emergency Fund', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15259, 210, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15265, 211, 'Business', 'Inventory Purchase', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15271, 212, 'Personal', 'Debt Consolidation', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15277, 213, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15283, 214, 'Business', 'Franchise Investment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15289, 215, 'Personal', 'Medical Bills', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15295, 216, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15301, 217, 'Business', 'Marketing Strategy', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15307, 218, 'Personal', 'Home Improvement', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15313, 219, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15319, 220, 'Business', 'Equipment Financing', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15325, 221, 'Personal', 'Emergency Fund', 'P');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15331, 222, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15337, 223, 'Business', 'Livestock Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15343, 224, 'Personal', 'Debt Consolidation', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15349, 225, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15355, 226, 'Business', 'New Equipment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15361, 227, 'Personal', 'Home Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15367, 228, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15373, 229, 'Business', 'Expansion Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15379, 230, 'Personal', 'Car Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15385, 231, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15391, 232, 'Business', 'Operational Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15397, 233, 'Personal', 'Emergency Fund', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15403, 234, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15409, 235, 'Business', 'Inventory Purchase', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15415, 236, 'Personal', 'Debt Consolidation', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15421, 237, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15427, 238, 'Business', 'Franchise Investment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15433, 239, 'Personal', 'Medical Bills', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15439, 240, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15445, 241, 'Business', 'Marketing Strategy', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15451, 242, 'Personal', 'Home Improvement', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15457, 243, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15463, 244, 'Business', 'Equipment Financing', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15469, 245, 'Personal', 'Emergency Fund', 'P');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15475, 246, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15481, 247, 'Business', 'Livestock Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15487, 248, 'Personal', 'Debt Consolidation', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15493, 249, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15499, 250, 'Business', 'New Equipment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15505, 251, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15511, 252, 'Business', 'New Equipment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15517, 253, 'Personal', 'Home Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15523, 254, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15529, 255, 'Business', 'Expansion Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15535, 256, 'Personal', 'Car Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15541, 257, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15547, 258, 'Business', 'Operational Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15553, 259, 'Personal', 'Emergency Fund', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15559, 260, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15565, 261, 'Business', 'Inventory Purchase', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15571, 262, 'Personal', 'Debt Consolidation', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15577, 263, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15583, 264, 'Business', 'Franchise Investment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15589, 265, 'Personal', 'Medical Bills', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15595, 266, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15601, 267, 'Business', 'Marketing Strategy', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15607, 268, 'Personal', 'Home Improvement', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15613, 269, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15619, 270, 'Business', 'Equipment Financing', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15625, 271, 'Personal', 'Emergency Fund', 'P');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15631, 272, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15637, 273, 'Business', 'Livestock Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15643, 274, 'Personal', 'Debt Consolidation', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15649, 275, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15655, 276, 'Business', 'New Equipment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15661, 277, 'Personal', 'Home Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15667, 278, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15673, 279, 'Business', 'Expansion Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15679, 280, 'Personal', 'Car Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15685, 281, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15691, 282, 'Business', 'Operational Costs', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15697, 283, 'Personal', 'Emergency Fund', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15703, 284, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15709, 285, 'Business', 'Inventory Purchase', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15715, 286, 'Personal', 'Debt Consolidation', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15721, 287, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15727, 288, 'Business', 'Franchise Investment', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15733, 289, 'Personal', 'Medical Bills', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15739, 290, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15745, 291, 'Business', 'Marketing Strategy', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15751, 292, 'Personal', 'Home Improvement', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15757, 293, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15763, 294, 'Business', 'Equipment Financing', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15769, 295, 'Personal', 'Emergency Fund', 'P');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15775, 296, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15781, 297, 'Business', 'Livestock Purchase', 'D');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15787, 298, 'Personal', 'Debt Consolidation', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15793, 299, 'Student', 'Education', 'A');

INSERT INTO LOAN_APPLICATION (APPLICATION_ID, CUSTOMER_ID, LOAN_TYPE, PURPOSE_OF_LOAN, APPLICATION_STATUS)
VALUES (15799, 300, 'Business', 'New Equipment', 'A');

