INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (1, 'Daniel', 'Figueroa', '072867825', '21819 Johnson Course', TO_DATE('1992-11-14', 'YYYY-MM-DD'), 'williamjohnson@baldwin.net', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (2, 'Jeffrey', 'Lawrence', '075614226', '65423 Garcia Light', TO_DATE('1977-11-27', 'YYYY-MM-DD'), 'melanie94@blair.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (3, 'Christian', 'Carter', '074744854', '310 Kendra Common Apt. 164', TO_DATE('1975-02-12', 'YYYY-MM-DD'), 'francisco53@hotmail.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (4, 'Jacqueline', 'Sutton', '072719583', '283 Steven Groves', TO_DATE('1967-07-11', 'YYYY-MM-DD'), 'megan03@trujillo.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (5, 'Jason', 'Hahn', '078078673', '76724 John Points Suite 969', TO_DATE('1953-11-11', 'YYYY-MM-DD'), 'jeffrey28@yahoo.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (6, 'Katelyn', 'Callahan', '071499914', '269 Paul Ranch', TO_DATE('1955-07-18', 'YYYY-MM-DD'), 'tasha01@hotmail.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (7, 'Karen', 'Mack', '074668136', '46270 Stanton Track Apt. 814', TO_DATE('1985-11-24', 'YYYY-MM-DD'), 'nathanielmartin@sellers.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (8, 'Natasha', 'Decker', '079478454', '03911 Cabrera Trace Apt. 278', TO_DATE('1974-01-21', 'YYYY-MM-DD'), 'allison96@hickman.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (9, 'Larry', 'Carney', '074335942', '8713 Caleb Brooks Apt. 930', TO_DATE('1997-11-15', 'YYYY-MM-DD'), 'perezrebecca@jones-young.info', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (10, 'Amber', 'Cummings', '074698379', '76311 Gomez Loop Suite 010', TO_DATE('1963-12-08', 'YYYY-MM-DD'), 'lauren13@gmail.com', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (11, 'Amanda', 'Taylor', '075667265', '7317 Brent Plains', TO_DATE('1962-04-20', 'YYYY-MM-DD'), 'housemelinda@russell.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (12, 'Rachel', 'Martin', '073678638', '4746 Moore Hill', TO_DATE('1976-08-24', 'YYYY-MM-DD'), 'rileyamy@edwards.net', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (13, 'Brian', 'Romero', '076708456', '91361 Beth Canyon', TO_DATE('1960-01-27', 'YYYY-MM-DD'), 'ksandoval@stewart.com', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (14, 'Joseph', 'Anderson', '073608513', '5107 Charles Forest Suite 251', TO_DATE('1965-08-07', 'YYYY-MM-DD'), 'justin78@turner.net', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (15, 'Elizabeth', 'Spencer', '076647119', '41182 Campbell Fords', TO_DATE('1949-11-21', 'YYYY-MM-DD'), 'gracefarrell@hotmail.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (16, 'John', 'Odonnell', '072556017', '64005 Dana Greens', TO_DATE('1982-08-08', 'YYYY-MM-DD'), 'barnold@smith.com', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (17, 'Barry', 'Wood', '072622631', '2045 Rachel Fords', TO_DATE('1986-06-26', 'YYYY-MM-DD'), 'gomezanita@dickson-brady.com', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (18, 'Theresa', 'Cochran', '076770619', '25634 Kristin Coves Suite 073', TO_DATE('1960-06-01', 'YYYY-MM-DD'), 'ybailey@walker.com', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (19, 'Mark', 'Lin', '071728977', '8685 Darrell Green Apt. 940', TO_DATE('1976-06-21', 'YYYY-MM-DD'), 'yreed@graham-joyce.com', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (20, 'Rachel', 'Lee', '079996414', '608 Michael Cliff', TO_DATE('1975-07-28', 'YYYY-MM-DD'), 'elizabeth14@hotmail.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (21, 'Elizabeth', 'Nguyen', '077350753', '236 Byrd Extensions Suite 680', TO_DATE('1970-05-28', 'YYYY-MM-DD'), 'jason99@hotmail.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (22, 'Steven', 'Ramos', '075918715', '721 Robertson Roads', TO_DATE('1971-04-15', 'YYYY-MM-DD'), 'cardenaskaren@hotmail.com', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (23, 'Jeffrey', 'Gonzalez', '074226067', '37917 Mercado Ports', TO_DATE('1970-06-25', 'YYYY-MM-DD'), 'psnyder@douglas.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (24, 'Ronald', 'Thompson', '071768805', '83172 Contreras Points Suite 798', TO_DATE('2002-04-30', 'YYYY-MM-DD'), 'vmerritt@yahoo.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (25, 'Jonathon', 'Wright', '075855124', '734 Jones Heights Apt. 455', TO_DATE('1979-12-26', 'YYYY-MM-DD'), 'edwardreyes@mccarthy.biz', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (26, 'Mark', 'Owens', '074905582', '66909 Woods Knoll', TO_DATE('1977-02-03', 'YYYY-MM-DD'), 'acastaneda@hotmail.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (27, 'Jessica', 'Marsh', '077377459', '3467 Paul Skyway', TO_DATE('2000-03-23', 'YYYY-MM-DD'), 'marycalhoun@hotmail.com', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (28, 'Anthony', 'Long', '078606962', '62720 Gray Forest', TO_DATE('1985-09-14', 'YYYY-MM-DD'), 'matthew64@yahoo.com', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (29, 'Mary', 'Ruiz', '073728882', '3100 James Brooks', TO_DATE('1966-07-11', 'YYYY-MM-DD'), 'davidcaldwell@gould.com', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (30, 'Catherine', 'Stuart', '076960453', '41904 Sanders Stravenue', TO_DATE('1960-10-10', 'YYYY-MM-DD'), 'vargasmaria@garcia.org', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (31, 'David', 'Riggs', '075479144', '8651 Smith Manor', TO_DATE('2004-03-04', 'YYYY-MM-DD'), 'hamiltonmichael@yahoo.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (32, 'Eric', 'Thompson', '073871230', '877 Petersen Ramp Suite 531', TO_DATE('1997-06-28', 'YYYY-MM-DD'), 'dsanchez@hotmail.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (33, 'Elizabeth', 'Rogers', '073741438', '2735 Peterson Ranch Suite 808', TO_DATE('1990-11-21', 'YYYY-MM-DD'), 'allenrichard@chang.info', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (34, 'Laura', 'Davis', '077366205', '3495 Tran Key', TO_DATE('1979-11-09', 'YYYY-MM-DD'), 'michael74@yahoo.com', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (35, 'Jerry', 'Griffith', '074684531', '82337 Hardy Trace Suite 134', TO_DATE('1966-06-19', 'YYYY-MM-DD'), 'harry08@hill.net', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (36, 'Heidi', 'Martinez', '071938483', '09477 Peterson Center Suite 711', TO_DATE('1969-03-28', 'YYYY-MM-DD'), 'ojones@hotmail.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (37, 'Edward', 'Shepherd', '071538552', '31869 Kimberly Light Suite 749', TO_DATE('1953-01-02', 'YYYY-MM-DD'), 'ashley09@hotmail.com', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (38, 'Stacey', 'Clark', '077730428', '1232 Eric Lodge', TO_DATE('1956-02-10', 'YYYY-MM-DD'), 'ocarter@yahoo.com', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (39, 'Justin', 'Heath', '072110460', '349 Ronald Plains', TO_DATE('1997-06-19', 'YYYY-MM-DD'), 'rebekahserrano@brown.org', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (40, 'Madison', 'Morse', '076279418', '74648 Kim Rapid Apt. 659', TO_DATE('2000-04-28', 'YYYY-MM-DD'), 'davissuzanne@hotmail.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (41, 'Stephanie', 'Key', '079375710', '027 Moon Falls Suite 717', TO_DATE('1989-04-24', 'YYYY-MM-DD'), 'qcook@gmail.com', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (42, 'Mark', 'Steele', '078698256', '680 Miller Glen Suite 168', TO_DATE('1960-04-20', 'YYYY-MM-DD'), 'mgutierrez@cox.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (43, 'Joseph', 'Anderson', '075443951', '7109 Jennifer Inlet Apt. 861', TO_DATE('1963-03-18', 'YYYY-MM-DD'), 'murraydavid@jimenez.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (44, 'Janice', 'Perry', '075137722', '3782 Lee Rapid Apt. 146', TO_DATE('1983-12-27', 'YYYY-MM-DD'), 'lori44@hotmail.com', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (45, 'Yolanda', 'Burns', '078187926', '8755 Gibson Islands', TO_DATE('1988-10-27', 'YYYY-MM-DD'), 'ashleyhall@williams-garner.biz', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (46, 'Vanessa', 'Sparks', '077073292', '0289 Kane Well', TO_DATE('1975-08-19', 'YYYY-MM-DD'), 'foxstephen@hotmail.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (47, 'Robert', 'Pena', '073320821', '74596 Melissa Walk', TO_DATE('1959-03-03', 'YYYY-MM-DD'), 'courtney78@gmail.com', 'N');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (48, 'Casey', 'Welch', '072525206', '16117 Heather Burgs Apt. 504', TO_DATE('1991-05-18', 'YYYY-MM-DD'), 'ryan38@yahoo.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (49, 'Erin', 'White', '072839607', '96937 Jesse Route', TO_DATE('1987-11-14', 'YYYY-MM-DD'), 'ascott@yahoo.com', 'Y');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_LNAME, CUSTOMER_CELLNUM, CUSTOMER_ADDRESS, CUSTOMER_DATE_OF_BIRTH, CUSTOMER_EMAIL, ACTIVE_STATUS)
VALUES (50, 'Erica', 'Moore', '073684052', '9464 Bruce Flat Suite 713', TO_DATE('1968-12-06', 'YYYY-MM-DD'), 'bailey40@hotmail.com', 'N');