-- this are our triggers for auto-incrementing primary keys
CREATE OR REPLACE TRIGGER customer_id_trigger
BEFORE INSERT ON CUSTOMER
FOR EACH ROW
BEGIN
    SELECT customer_id_seq.NEXTVAL INTO :NEW.CUSTOMER_ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER employee_id_trigger
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
    SELECT employee_id_seq.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER account_id_trigger
BEFORE INSERT ON ACCOUNT
FOR EACH ROW
BEGIN
    SELECT account_id_seq.NEXTVAL INTO :NEW.ACCOUNT_ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER transaction_id_trigger
BEFORE INSERT ON TRANSACTION
FOR EACH ROW
BEGIN
    SELECT transaction_id_seq.NEXTVAL INTO :NEW.TRANSACTION_ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER card_id_trigger
BEFORE INSERT ON CARD
FOR EACH ROW
BEGIN
    SELECT card_id_seq.NEXTVAL INTO :NEW.CARD_ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER group_acc_id_trigger
BEFORE INSERT ON GROUP_ACCOUNT
FOR EACH ROW
BEGIN
    SELECT group_id_seq.NEXTVAL INTO :NEW.GROUP_ID FROM dual;
END;
/



CREATE OR REPLACE TRIGGER application_id_trigger
BEFORE INSERT ON LOAN_APPLICATION
FOR EACH ROW
BEGIN
    SELECT application_id_seq.NEXTVAL INTO :NEW.APPLICATION_ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER assessment_id_trigger
BEFORE INSERT ON CREDIT_RISK_ASSESSMENT
FOR EACH ROW
BEGIN
    SELECT assessment_id_seq.NEXTVAL INTO :NEW.ASSESSMENT_ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER loan_id_trigger
BEFORE INSERT ON LOAN
FOR EACH ROW
BEGIN
    SELECT loan_id_seq.NEXTVAL INTO :NEW.LOAN_ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER repayment_id_trigger
BEFORE INSERT ON LOAN_REPAYMENT
FOR EACH ROW
BEGIN
    SELECT repayment_id_seq.NEXTVAL INTO :NEW.REPAYMENT_ID FROM dual;
END;
/



